function trendData = importTrendOutput(trendFile)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 20-Aug-2012 11:29:10

DELIMITER = ',';
HEADERLINES = 4;

%Import the file
trendData = importdata(trendFile, DELIMITER, HEADERLINES);

